version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80/tcp"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      # - ./static:/staticfiles
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - secret_key=django-insecure-@%*ewvv4vw8o9x)s_8n75^yaiym*myk)*foi4kx7opczjq5n8&
    container_name: web
    command: gunicorn config.wsgi:application --bind 0:8000
    # volumes:
    #   - ./static:/usr/src/app/staticfiles
    expose:
      - "8000"
      